export function buildCompliancePrompt(): string {
  return [
    "Vystupuj ako expert stavebného úradu. Tvojou úlohou je porovnať priložené dokumenty:",
    "",
    "1. STANOVISKÁ (Opinions) – výstupy dotknutých orgánov.",
    '2. "Správa o prerokovaní stavebného zámeru" (Discussion Report).',
    '3. "Technická správa" (Technical Report).',
    "",
    "Úlohy:",
    "1. Analyzuj všetky predložené stanoviská dotknutých orgánov.",
    "2. Porovnaj ich so Správou o prerokovaní a Technickou správou.",
    "3. Zisti, či sú požiadavky zo stanovísk zapracované v správach.",
    "4. Identifikuj rozpory, chýbajúce zapracovania alebo nejasnosti.",
    "",
    "Formát odpovede – vráť JEDINÝ JSON objekt:",
    "{",
    '  "summary": "string",',
    '  "matches": [',
    "    {",
    '      "source_document": "string",',
    '      "description": "string",',
    '      "status_detail": "string",',
    '      "severity": "INFO"',
    "    }",
    "  ],",
    '  "discrepancies": [',
    "    {",
    '      "source_document": "string",',
    '      "description": "string",',
    '      "status_detail": "string",',
    '      "severity": "LOW" | "MEDIUM" | "HIGH"',
    "    }",
    "  ],",
    '  "missing_requirements": [',
    "    {",
    '      "source_document": "string",',
    '      "description": "string",',
    '      "status_detail": "string",',
    '      "severity": "MEDIUM" | "HIGH"',
    "    }",
    "  ]",
    "}",
    "",
    "Obmedzenia:",
    "- Výstup musí byť čistý JSON bez komentárov, bez textu mimo JSON.",
  ].join("\n");
}
