export function buildDiscussionReportPrompt(): string {
  return [
    'Vystupuj ako hlavný inžinier projektu. Tvojou úlohou je vypracovať "Správu o prerokovaní stavebného zámeru" na základe priložených stanovísk.',
    "",
    "Správa MUSÍ obsahovať kapitoly presne podľa prílohy č. 16 vyhlášky č. 60/2025 Z. z.:",
    "A. Zoznam dotknutých orgánov a osôb (identifikuj ich z hlavičiek dokumentov).",
    "B. Zoznam doručených stanovísk (pre každý dokument extrahuj názov orgánu, dátum, obsah a podmienky).",
    "C. Informácia o orgánoch, ktoré sa nevyjadrili (ak to z dokumentov nie je zrejmé, nechaj pole prázdne).",
    "D. Vyhodnotenie stanovísk projektantom (napíš profesionálny text, že pripomienky boli vyhodnotené a zapracované do dokumentácie).",
    "E. Zhrnutie súladu (napíš formálne prehlásenie, že zámer bol prerokovaný a je v súlade s predpismi).",
    "F. Podpisová doložka (text informujúci o potrebe podpisu projektanta a stavebníka).",
    "",
    "Vstupom sú textové znenia jednotlivých stanovísk (Opinions).",
    "",
    "Formát odpovede – vráť JEDINÝ JSON objekt:",
    "{",
    '  "A_authorities_list": [',
    "    {",
    '      "name": "string",',
    '      "date_contacted": "string"',
    "    }",
    "  ],",
    '  "B_delivered_opinions": [',
    "    {",
    '      "authority_name": "string",',
    '      "delivery_date": "string",',
    '      "content_summary": "string",',
    '      "conditions": ["string"]',
    "    }",
    "  ],",
    '  "C_silent_authorities": ["string"],',
    '  "D_projection_evaluation": "string",',
    '  "E_compliance_summary": "string",',
    '  "F_signatures_placeholder": "string"',
    "}",
    "",
    "Obmedzenia:",
    "- Výstup musí byť čistý JSON bez komentárov, bez textu mimo JSON.",
  ].join("\n");
}
