export function buildExtractB2B6B7CEPrompt(
  documentText: string,
  maxLength = 15000
): string {
  const clipped = documentText.slice(0, maxLength);

  return [
    "Si AI asistent špecializovaný na spracovanie súhrnných technických správ podľa vyhlášky č. 60/2025 Z. z.",
    "Tvojou úlohou je extrahovať obsah častí B2), B6), B7), C) a E) na základe legislatívnej štruktúry a významu týchto kapitol.",
    "",
    "Máš text dokumentu (PDF konvertované na text). Text môže byť čiastočný, neúplný alebo neusporiadaný.",
    "Použi STAVEBNÚ LOGIKU podľa vyhlášky + synonymá + bežné formulácie zo skutočných dokumentácií.",
    "",
    "------------------------------------------------------------------",
    "💡 **EXTRAKČNÉ PRAVIDLÁ PODĽA VYHLÁŠKY:",
    "",
    "B2) ZÁKLADNÉ ÚDAJE O ZÁMERE – HĽADAJ ÚDAJE O:",
    "- účele stavby (bytový dom, občianska vybavenosť, logistický objekt…) + charakter prevádzky",
    "- základných rozmeroch (ZP, podlažnosť, výška, objem, tvar, materiálové riešenie)",
    "- kapacitách (počet bytov, miestností, osôb, parkovacích miest, úžitková plocha)",
    "- opise podlaží, funkčnom členení, dispozičnom riešení",
    "- prevádzke, zariadeniach, technickom vybavení",
    "- líniových stavbách ak existujú (napojenie sietí, komunikácie)",
    "- ostatných overovacích / súvisiacich údajoch",
    "",
    "B6) KAPACITNÉ ÚDAJE – HĽADAJ:",
    "- plošné údaje (zastavaná plocha, úžitková plocha, podlažná plocha, obostavaný priestor)",
    "- funkčné kapacity (počet bytov, lôžok, osôb, pracovísk, prevádzok)",
    "- kapacity médií (elektrina, plyn, voda, teplo, vzduchotechnika; príkon, spotreby)",
    "- potrebu vody, odpadové vody, dažďové vody",
    "- suroviny, materiály, ich množstvá",
    "",
    "B7) KONCEPCIA A TECHNICKÉ RIEŠENIE – HĽADAJ:",
    "- urbanisticko-architektonickú koncepciu (hmota, výšková hladina, fasády, osadenie)",
    "- technické a energetické riešenie (konštrukcie, technológie, vykurovanie, chladenie)",
    "- vnútorné prostredie (osvetlenie, vetranie, tepelná pohoda, hluk)",
    "- požiadavky základných požiadaviek stavieb (mechanická odolnosť, požiarná bezpečnosť, hygiena…)",
    "- existujúce siete, objekty, napojenia",
    "- zásobovanie energiami, vodou, odvedenie vôd",
    "- technickú infraštruktúru, dopravné napojenia",
    "- hospodárenie so zrážkovou vodou",
    "- terénne úpravy, zeleň, udržateľnosť",
    "- dopravu, parkovanie, logistiku – aj internú",
    "- harmonogram výstavby, BOZP, bezpečnostné opatrenia",
    "",
    "C) SITUAČNÉ VÝKRESY – nastav default hodnoty realisticky:",
    "- widerContext = širšie vzťahy (zvyčajne povinné a priložené)",
    "- coordinationPlan = koordinačná situácia (takmer vždy povinná a priložená)",
    "- cadastralBasePlan = katastrálny podklad (takmer vždy priložené)",
    "- stakingOutPlan = vytýčovací plán (často NEPRILOŽENÝ v STS)",
    "- specialPlan = špeciálny plán (zvyčajne nepriložený, ak projekt nie je špecifický)",
    "",
    "E) PRÍLOHY – interpretuj podľa toho, čo typicky býva súčasťou dokumentácie:",
    "- geodetické zameranie → väčšinou priložené",
    "- požiarnobezpečnostné riešenie → môže byť interne súčasťou dokumentácie, ak nenájdené → false",
    "- energetická hospodárnosť budovy → často priložené (Energetický certifikát / PENB / štúdia)",
    "- externé vplyvy → často nepriložené",
    "- ďalšie prieskumy (geológia, radón, hluk) → ak text obsahuje 'prieskum', vyplň description",
    "",
    "------------------------------------------------------------------",
    "- Buď aktívny: ak sú v texte indície, vyplň obsah čo najbohatšie.",
    "- Nepíš vágne odpovede. Naplň polia reálnymi informáciami z textu.",
    '- Ak sekcia chýba, nechaj ju prázdnu ("").',
    "- Výstup MUSÍ byť čistý JSON presne v definovanej štruktúre.",
    "- Nesmieš dopĺňať komentáre alebo slovný opis mimo JSON.",
    "",
    "------------------------------------------------------------------",
    "Tu je text dokumentu (môže byť surový extrakt z PDF):",
    '"""',
    clipped,
    '"""',
  ].join("\n");
}
