export const FILE_NAMING_RULES_CONTEXT = [
  "Úloha: skontroluj názvy dokumentov podľa požiadaviek stavebného zákona.",
  "Pravidlá:",
  "1) Podľ zákona 60/2025 Z. z. a dokumentu https://static.slov-lex.sk/pdf/prilohy/SK/ZZ/2025/60/vyhlasene_znenie_5721403-2.pdf. skontroluj názvy súborov.",
  "2) Pri každom súbore rozhodni, či je názov OK alebo odporúčaš premenovanie.",
  "3) Ak odporúčaš zmenu, navrhni nový názov bez diakritiky, s podčiarkovníkmi, bez duplicitných prípon.",
  "4) Systémové alebo zbytočné súbory (napr. .DS_Store) označ tak, že nový názov začne na DELETE_.",
  "",
  'Dodatočné pravidlá pre štruktúru názvov súborov na 9 pozíciách oddelených znakom "_":',
  "",
  "Pozícia 1 = ID stavby (napr. 25AB123) – 7 znakov pridelených informačným systémom.",
  "Pozícia 2 = Stupeň dokumentácie stavby (3 písmená, bez medzier):",
  "  PSO = Projekt stavby na ohlásenie",
  "  SZP = Stavebný zámer",
  "  SZZ = Zmena stavebného zámeru",
  "  PSP = Projekt stavby",
  "  PSZ = Zmena projektu stavby",
  "  VPP = Vykonávací projekt",
  "  RDS = Realizačná dokumentácia stavby (výrobná príprava zhotoviteľa a stavebný denník)",
  "  DSZ = Dokumentácia skutočného zhotovenia",
  "  ZDS = Zjednodušená dokumentácia stavby (pasport stavby)",
  "",
  "Pozícia 3 = Určenie stavby alebo súboru stavieb (2 číslice):",
  "  01 = Samostatná stavba alebo stavba č. 1 – hlavná stavba pri súbore stavieb",
  "  02 = Stavba č. 2 pri súbore stavieb",
  "  03 = Stavba č. 3 pri súbore stavieb",
  "",
  "Pozícia 4 = Identifikačný kód stavby (4 číslice) podľa vyhlášky o členení stavieb (príklady):",
  "  1111 = Jednobytové budovy",
  "  1112 = Dvojbytové budovy",
  "  1211 = Hotelové budovy",
  "",
  "Pozícia 5 = Základné členenie dokumentácie stavby a členenie stavby:",
  "  A00 = Zoznam dokumentácie",
  "  B00 = Súhrnná správa",
  "  C00 = Situačné výkresy stavby",
  "  E00 = Prílohy a posúdenia",
  "  S01, S02, S03, ... = Číslo stavebného objektu",
  "  P01, P02, P03, ... = Číslo prevádzkového súboru",
  "",
  "Pozícia 6 = Podrobné členenie dokumentácie a profesie (3 písmená, bez medzier):",
  "  Pre A00:",
  "    AAA = Zoznam dokumentácie",
  "  Pre B00:",
  "    SPR = Súhrnná správa",
  "  Pre C00:",
  "    SIT = Situácia",
  "  Pre Sxx – profesie základné:",
  "    ASR = Architektonicko-stavebné riešenie",
  "    STA = Statika",
  "    ZTI = Zdravotechnická inštalácia",
  "    VYK = Vykurovanie",
  "    PLY = Plynoinštalácia",
  "    VZT = Vzduchotechnika a chladenie",
  "    MAR = Meranie a regulácia",
  "    ELI = Elektroinštalácia",
  "    BLZ = Bleskozvod a uzemnenie",
  "    SLP = Slaboprúdová inštalácia, štruktúrované káblové rozvody",
  "    HSP = Hlasová signalizácia požiaru",
  "    EPS = Elektrická požiarna signalizácia",
  "    SHZ = Stabilné hasiace zariadenia",
  "    ODT = Zariadenie na odvod dymu a tepla",
  "    USV = Umelé osvetlenie",
  "    KRA = Krajinné, sadové a terénne úpravy",
  "    DOP = Dopravné riešenie",
  "    POD = Projekt organizácie dopravy",
  "    TDZ = Trvalé dopravné značenie",
  "    DDZ = Dočasné dopravné značenie",
  "  Profesie areálové:",
  "    PNN = Elektrická prípojka nízkeho napätia",
  "    PVN = Elektrická prípojka vysokého napätia",
  "    VUO = Vonkajšie / verejné osvetlenie",
  "    ARS = Areálové / miestne rozvody silnoprúdu",
  "    AEK = Areálové / miestne rozvody elektronických komunikácií",
  "    REK = Rozvody elektronických komunikácií",
  "    VDS = Vedenia distribučnej sústavy",
  "  Profesie špecializované:",
  "    BK = Betónové konštrukcie",
  "    OK = Oceľové konštrukcie",
  "    SKV = Systém kontroly vstupu",
  "    EZS = Elektrická zabezpečovacia signalizácia",
  "    UTO = Uzatvorený televízny okruh (CCIR)",
  "    HSR = Hotelový systém riadenia",
  "    NKS = Nemocničný komunikačný systém",
  "    SKR = Systém riadenia procesov (SRTP, ASRTP, SKR)",
  "    CRS = Centrálne riadiace systémy budov (BMS)",
  "    ADR = Automatický systém dispečerského riadenia (ASDR)",
  "    ZDT = Zdravotnícka technológia",
  "    RTG = Projekt radiačnej ochrany",
  "    MED = Medicinálne plyny",
  "    TGZ = Výrobné technologické zariadenia",
  "    ETS = Elektrická stanica",
  "    PRS = Prevádzkový rozvod silnoprúdu",
  "    NZE = Náhradný zdroj elektrickej energie",
  "    FVZ = Fotovoltický zdroj (výkon meniča do 10 kW)",
  "    FVE = Fotovoltická elektráreň (výkon meniča nad 10 kW)",
  "    KGZ = Kogeneračný zdroj / KVET",
  "    BAT = Batériové úložisko",
  "    KTO = Katódová ochrana",
  "    INE = Iná profesia vyššie neuvedená",
  "  Pre E00 – prílohy a posúdenia:",
  "    SZS = Správa o prerokovaní stavebného zámeru",
  "    STD = Stavebný denník",
  "    ZSS = Záverečné stanovisko stavbyvedúceho",
  "    PBS = Protipožiarna bezpečnosť stavby",
  "    POV = Plán organizácie výstavby",
  "    STP = Protokol z kontrolného statického posúdenia / svetelno-technické riešenie umelého osvetlenia",
  "    GDP = Geodetické podklady",
  "    PAM = Pamiatkový výskum",
  "    EIA = Posúdenie vplyvov na životné prostredie",
  "    EHB = Energetické hodnotenie budovy",
  "    DEN = Dendrologické posúdenie",
  "    DEV = Náhradná výsadba drevín",
  "    SVP = Svetelno-technické posúdenie",
  "    HGP = Hydrogeologické posúdenie",
  "    IGP = Inžinierskogeologické posúdenie",
  "    HLU = Hluková štúdia",
  "    IPP = Imisno-prenosové (rozptylová štúdia) posúdenie",
  "    PEZ = Prieskum environmentálnej záťaže",
  "    ECB = Energetický certifikát budovy",
  "    INE = Iné posúdenie vyššie neuvedené",
  "",
  "Pozícia 7 = Číslo dokumentu alebo výkresu (3 číslice):",
  "  000 = Zoznam výkresov, súhrnná správa, technická správa",
  "  001, 002, ... = Číslo výkresu, dokumentu alebo prílohy podľa poradia",
  "",
  "Pozícia 8 = Názov dokumentu alebo výkresu (3 znaky):",
  "  AAA = Zoznam dokumentov a výkresov",
  "  TXT = Technická správa",
  "  SIT = Situácia",
  "  VYT = Vytyčovací výkres",
  "  VYZ = Výkres základov",
  "  VYS = Výkres strechy",
  "  STV = Kontrolovateľný statický výpočet",
  "  N01 = Pôdorys 1. nadzemného podlažia alebo pôdorys č. 1",
  "  N02 = Pôdorys 2. nadzemného podlažia alebo pôdorys č. 2",
  "  P01 = Pôdorys 1. podzemného podlažia",
  "  P02 = Pôdorys 2. podzemného podlažia",
  "  POH = Pohľad",
  "  REZ = Rez",
  "  VIZ = Vizualizácia",
  "  DET = Detail",
  "  SCH = Schéma",
  "  VVZ = Výkaz výrobkov a zariadení, výkaz prvkov",
  "  VYV = Výkaz výmer",
  "  ROZ = Rozpočet",
  "",
  "Pozícia 9 = Revízia dokumentu alebo výkresu (2 číslice):",
  "  00 = Prvé vydanie dokumentu / výkresu / schémy (nie je potrebné uvádzať)",
  "  01, 02, 03, ... = Číslo revízie dokumentu / výkresu / schémy.",
].join("\n");
